[project]
name = "test"
authors = []
description = ""
telemetry = true

[contracts.bit-swap]
path = "contracts/bitSwap.clar"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
